package mixnet

const EventVersionPrefix = "v2_"

type MixnetEventType string

const (
	MixnodeBondingEvent                       MixnetEventType = EventVersionPrefix + "mixnode_bonding"
	NymNodeBondingEvent                       MixnetEventType = EventVersionPrefix + "nymnode_bonding"
	NymNodeUnbondingEvent                     MixnetEventType = EventVersionPrefix + "nymnode_unbonding"
	PendingNymNodeUnbondingEvent              MixnetEventType = EventVersionPrefix + "pending_nymnode_unbonding"
	GatewayMigrationEvent                     MixnetEventType = EventVersionPrefix + "gateway_migration"
	MixnodeMigrationEvent                     MixnetEventType = EventVersionPrefix + "mixnode_migration"
	PendingPledgeIncreaseEvent                MixnetEventType = EventVersionPrefix + "pending_pledge_increase"
	PledgeIncreaseEvent                       MixnetEventType = EventVersionPrefix + "pledge_increase"
	PendingPledgeDecreaseEvent                MixnetEventType = EventVersionPrefix + "pending_pledge_decrease"
	PledgeDecreaseEvent                       MixnetEventType = EventVersionPrefix + "pledge_decrease"
	GatewayBondingEvent                       MixnetEventType = EventVersionPrefix + "gateway_bonding"
	GatewayUnbondingEvent                     MixnetEventType = EventVersionPrefix + "gateway_unbonding"
	PendingMixnodeUnbondingEvent              MixnetEventType = EventVersionPrefix + "pending_mixnode_unbonding"
	MixnodeUnbondingEvent                     MixnetEventType = EventVersionPrefix + "mixnode_config_update"
	MixnodeConfigUpdateEvent                  MixnetEventType = EventVersionPrefix + "mixnode_unbonding"
	PendingCostParamsUpdateEvent              MixnetEventType = EventVersionPrefix + "pending_cost_params_update"
	CostParamsUpdateEvent                     MixnetEventType = EventVersionPrefix + "cost_params_update"
	NodeRewardingEvent                        MixnetEventType = EventVersionPrefix + "node_rewarding"
	WithdrawDelegatorRewardEvent              MixnetEventType = EventVersionPrefix + "withdraw_delegator_reward"
	WithdrawOperatorRewardEvent               MixnetEventType = EventVersionPrefix + "withdraw_operator_reward"
	PendingActiveSetUpdateEvent               MixnetEventType = EventVersionPrefix + "pending_active_set_update"
	ActiveSetUpdateEvent                      MixnetEventType = EventVersionPrefix + "active_set_update"
	PendingIntervalRewardingParamsUpdateEvent MixnetEventType = EventVersionPrefix + "pending_interval_rewarding_params_update"
	IntervalRewardingParamsUpdateEvent        MixnetEventType = EventVersionPrefix + "interval_rewarding_params_update"
	PendingDelegationEvent                    MixnetEventType = EventVersionPrefix + "pending_delegation"
	PendingUndelegationEvent                  MixnetEventType = EventVersionPrefix + "pending_undelegation"
	DelegationEvent                           MixnetEventType = EventVersionPrefix + "delegation"
	DelegationOnUnbondingEvent                MixnetEventType = EventVersionPrefix + "undelegation"
	UndelegationEvent                         MixnetEventType = EventVersionPrefix + "settings_update"
	ContractSettingsUpdateEvent               MixnetEventType = EventVersionPrefix + "nym_node_semver_update"
	NymNodeSemverUpdateEvent                  MixnetEventType = EventVersionPrefix + "rewarding_validator_address_update"
	RewardingValidatorUpdateEvent             MixnetEventType = EventVersionPrefix + "beginning_epoch_transition"
	BeginEpochTransitionEvent                 MixnetEventType = EventVersionPrefix + "advance_epoch"
	AdvanceEpochEvent                         MixnetEventType = EventVersionPrefix + "role_assignment"
	RoleAssignmentEvent                       MixnetEventType = EventVersionPrefix + "execute_pending_epoch_events"
	ExecutePendingEpochEventsEvent            MixnetEventType = EventVersionPrefix + "execute_pending_interval_events"
	ExecutePendingIntervalEventsEvent         MixnetEventType = EventVersionPrefix + "reconcile_pending_events"
	ReconcilePendingEventsEvent               MixnetEventType = EventVersionPrefix + "pending_interval_config_update"
	PendingIntervalConfigUpdateEvent          MixnetEventType = EventVersionPrefix + "interval_config_update"
	IntervalConfigUpdateEvent                 MixnetEventType = EventVersionPrefix + "delegation_on_unbonding_node"
	GatewayConfigUpdateEvent                  MixnetEventType = EventVersionPrefix + "gateway_config_update"
)
